### ISSUE TITLE
there is something wrong

### ISSUE THREAD

**Issue by xiaoxiong007** [AgenaRisk/api#1]
when i run this demo in intellJIDEA, the error msg is 

AgenaRisk initialization failed: File not found: F:\yyy\lib\AgenaRisk.dat

yyy is the name of my project

**Comment by edemen** [comment]
Hi 
As it says in the readme, you need to trigger download of non java dependencies by doing mvn clean once 

You can either do it in the console ( mvn clean ) while in the project directory, or perform a clean build in intellJIDEA. This will download all the necessary files into project/lib directory

**Comment by xiaoxiong007** [comment]
------------------ 原始邮件 ------------------
发件人: "Eugene Dementiev"<notifications@github.com>;
发送时间: 2019年6月21日(星期五) 下午5:48
收件人: "AgenaRisk/api"<api@noreply.github.com>;
抄送: "xiaoxiong007"<1017697041@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [AgenaRisk/api] there is something wrong (#1)




Hi
 As it says in the readme, you need to trigger download of non java dependencies by doing mvn clean once
 
You can either do it in the console ( mvn clean ) while in the project directory, or perform a clean build in intellJIDEA. This will download all the necessary files into project/lib directory

**Comment by xiaoxiong007** [comment]
Are there any documents like quick start?

**Comment by edemen** [comment]
You can check the [example app](https://github.com/AgenaRisk/api-example-app) for a very basic example of how to use it for loading XML defined models.
This API is currently in development, so feel free to suggest the functionality you might need.

For reference, you can check the old [API manual](https://resources.agenarisk.com/materials/AgenaRisk%2010%20Developer%20User%20Manual.pdf) (usable with the example app linked above).
